trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - pipelines/propagator/config.yaml

resources:
  repositories:
  - repository: pipelines
    type: git
    name: platform-engineering-stack/common-pipelines
    ref: refs/tags/3.17.1

extends:
  template: pipelines-propagator/propagator.yaml@pipelines