trigger: none

parameters:
- name: environment
  type: string
  displayName: "Environment to deploy"
  default: dev
  values:
  - 'dev'
  - 'preprod'

variables:
  - template: vars-${{ parameters.environment }}.yaml

extends:
  template: pipelines-cd.yaml
  parameters:
    cluster: ${{variables.cluster}}
    serviceConn: ${{variables.serviceConn}}
    namespace: ${{variables.namespace}}
    environment: '${{parameters.environment}}'
    helmReleaseName: 'hello-world-java-svc'