trigger:
  branches:
    include:
    - 'main'

extends:
  template: pipelines-ci-tbd.yaml
  parameters:
    buildTool: 'maven'
    deployPipelineName: 'hello-world-java-service-CD'
    imageName: ''
    defaultBranch: 'main'
    envsToDeploy:
    - 'dev'