trigger:
  branches:
    include:
    - 'main'

extends:
  template: templates/pipelines-ci-tbd.yaml
  parameters:
    buildTool: 'maven'
    deployPipelineName: 'hello-world-java-service-CD'
    imageName: ''
    defaultBranch: 'main'
    environmentObjects:
    - serviceConn: 'demo-svc-conn-aks'
      acr: 'mydemoacr1604.azurecr.io'
      publishPRImages: true
    envsToDeploy:
    - 'dev'