apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deploy.name }}"
  labels:
    name: "{{ .Values.deploy.name }}"
    app: "{{ .Values.deploy.name }}"
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
  - name: http
    port: {{ .Values.config.port }}
    targetPort: {{ .Values.config.port }}
  selector:
    app: "{{ .Values.deploy.name }}"
